### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by HanaaGhasoub** [owsolutions/amazing-time-picker#109]
Dear @yousefsami 
i am using amazing-time-picker as stated here.
after installation done without any errors, i used directive as following :

- imported module to my module 
![image](https://user-images.githubusercontent.com/30862539/48943150-f0a7e500-ef2a-11e8-924e-63e65a8939e1.png)

- use directive 
![image](https://user-images.githubusercontent.com/30862539/48943164-00bfc480-ef2b-11e8-9178-40c8ded03d9e.png)

- try to run my project then faced this warning 
![image](https://user-images.githubusercontent.com/30862539/48943131-de2dab80-ef2a-11e8-9755-d1d274193608.png)
 , also this console error
![image](https://user-images.githubusercontent.com/30862539/48943218-36fd4400-ef2b-11e8-934b-ea2917218e6b.png)

> What i am missing here ?

my enviroment :
Windows10
Angular6

**Comment by torabian** [comment]
My recent tests shows this repo works fine with angular 6, 7.

Please provide more details or direct contact

**Comment by torabian** [comment]
I’ll do further investigations by tomorrow afternoon Europe time.
