### ISSUE TITLE
issue in Amazing Time Picker in Angular 7, with the bootstrap Modal

### ISSUE THREAD

**Issue by adithyasbhat** [owsolutions/amazing-time-picker#129]
When i use this Amazing Time picker in a web page it works fine,
but when i use amazing time picker inside the bootstrap modal in angular 7 
it displays behind the modal and i tried every possible way to bring it to the front by using Z-Index
but it didn't helped me that.

can anyone know how to solve this?
it would be more Helpful !!!

thanks,
Adithya
bhat.s.adithy@gmail.com

![i1](https://user-images.githubusercontent.com/31362040/58230303-99f05c00-7d51-11e9-8fbb-e64ebcabcab8.PNG)
![i2](https://user-images.githubusercontent.com/31362040/58230311-9f4da680-7d51-11e9-813a-756dda22ab4f.png)

**Comment by askynet** [comment]
use css
time-picker{
   position:absolute;
   z-index : 99999999;
}

**Comment by adithyasbhat** [comment]
thanks.
