### ISSUE TITLE
Time picker minute value needs zero fill

### ISSUE THREAD

**Issue by austin-bovee** [owsolutions/amazing-time-picker#31]
When choosing a single digit value on the clock, the digital clock display for the time-picker-minute isn't showing a leading zero. Example: 6:03 looks like 6:3
<img width="321" alt="screen shot 2018-01-18 at 9 15 13 am" src="https://user-images.githubusercontent.com/17326368/35105038-4043476a-fc30-11e7-8af2-9ca08dbef06e.png">

**Comment by torabian** [comment]
Thank you for replying this. This is a preference for styling, but when you close dialog, it will appear using 03. We can add a formatting function for this.

**Comment by austin-bovee** [comment]
A formatting function would be great, look forward to the addition, thanks.

**Comment by torabian** [comment]
I made a solution for this, and pull request is in preview. Hope to merge soon.

https://github.com/owsolutions/amazing-time-picker/pull/38

**Comment by torabian** [comment]
This is fixed since `1.4.3`. Please update your dependency.
