### ISSUE TITLE
Is it possible to add a title to the window?

### ISSUE THREAD

**Issue by Simbaclaws** [owsolutions/amazing-time-picker#41]
Let's say for example that I'm going to use this in conjunction with some other functionality in my code.

Can I somehow programatically add a title to the window?
For example, I have a calendar in which I want to set a start and end time of an activity, can I programatically show the window saying start time and end time so that the user knows what kind of time he/she is setting?

Also, is angular material a required dependency that I need to install in order to get this time picker to work? I'd like to keep my project small by not having to add extra frameworks that I'm barely going to use...

**Comment by torabian** [comment]
At the moment, we do not have a title in the time picker modal. If you think this is a good option to show it on top of the modal, then we can proceed to add this feature.
You can limit the user to not able to select times between start and end time, which is already working in master branch.

You do not need Angular Material to install this project, and time picker itself is not using it. We have tested this on Angular 4 and 5 with zero dependency.

**Comment by Simbaclaws** [comment]
Thanks a lot I would really appreciate a title in the window. If you want I could code it myself and make a pull request from a fork?
Or would you rather want to do it?

**Comment by torabian** [comment]
We think you it can be a feature but I don't think this is good to be as an initial because the modal gonna be longer than it is.
If you want to make a pull request, we would really appreciate it. Otherwise we can schedule to add this feature on 28th, if you do not open a pull request.
