### ISSUE TITLE
Angular 2...?

### ISSUE THREAD

**Issue by dannyb4** [owsolutions/amazing-time-picker#44]
Hi there, could you explain how this package is supposed to work with angular 2.X please? Looking through the package.json file you have only ever depended on angular version 4.2.4 and above...?

**Comment by torabian** [comment]
Thank you for your notice. We changed the dependenciies to Angular 2.5 so you must be able to get it from the master branch.

**Comment by torabian** [comment]
You can now install for angular 2 from `1.4.3` version.
