### ISSUE TITLE
Implement IDisplayPreference 

### ISSUE THREAD

**Issue by vagostep** [owsolutions/amazing-time-picker#46]
Hi, nice timepicker. I would wondering how to implements the interface IDisplayPreference in the open method to set labels titles. In the doc i can't find one clear explanation.

```
export interface IDisplayPreference {
    minute?: Function;
    hour?: Function;
    separator?: string;
    labels?: {
      ok?: string;
      cancel?: string;
    };
    period?(period: 'AM' | 'PM');
    clockMinute?(minute: any);
    clockHour?(hour: any);
  }
```

**Comment by torabian** [comment]
@vagostep Thank you so much for opening this issue. Apparently timepicker only gets the locale and reads preferences from `preference.ts`. That's what I have just noticed.
I have opened a new pull requests to add `preference` to accept a `IDisplayPreference` quickly and update here receptively.

**Comment by torabian** [comment]
Here is the pull request: #47 
Now you can make your own preference, for example:
```

export const MyPreference = {
  hour: (x) => persian.format(x),
  minute: (x) => {
    let exp = persian.format(x);
    if (exp.length === 1) {
      exp = '۰' + exp;
    }
    return exp;
  },
  separator: ':',
  period: (x) => x === 'AM' ? 'صبح' : 'عصر',
  clockHour: (x) => persian.format(x),
  clockMinute: (x) => persian.format(x),
  labels: {
    ok: 'تایید',
    cancel: 'لغو'
  }
};
```

and then, when you want to use timepicker:
```
<input type="time" atp-time-picker [preference]="MyPreference" />
```
or, if you want to open it using AmazingTimePickerService, pass the preference inside `open ` function:
```
  openMyDialogInsideMyComponent () {
    const amazingTimePicker = this.atp.open({preference: MyPreference});
    amazingTimePicker.afterClose().subscribe(time => {
      console.log(time);
    });
  }
```

**Comment by vagostep** [comment]
Thank you very much. I'll be waiting for the change to be uploaded

**Comment by yousefsami** [comment]
Hi @vagostep
Thank you for your attention. You can now use this feature from `1.4.4 ` version.
