### ISSUE TITLE
Is it possible to add the 24h format?

### ISSUE THREAD

**Issue by reschandreas** [owsolutions/amazing-time-picker#53]
Would be very nice

**Comment by torabian** [comment]
As a UX decision, we are not really happy to do that, because it's gonna make confusion for the user, specially affects the "On-Drag" system.
If you think this is necessary, please make a work around it and open a pull request, in a way this feature is an optional.

**Comment by AhHa45** [comment]
This is a must have! Otherwise it's useless.
