### ISSUE TITLE
Clicking clock occasionally does not update time / arrow

### ISSUE THREAD

**Issue by smitelij** [owsolutions/amazing-time-picker#55]
In the function CalcDegrees, line 103-105:

```
if (degMod === 0) {
      return;
}
```
You should instead return degrees here, otherwise we get an undefined return value.

**Comment by torabian** [comment]
What is the current behavior?

**Comment by smitelij** [comment]
Open amazing-time-picker. Switch to selecting minutes. Every 1 out of 6 clicks, the clock will not get updated with the new position.

**Comment by torabian** [comment]
Thank you for reporting this. Can you give me a hint how can I fix this issue?

**Comment by torabian** [comment]
I have fixed this issue. It will be available from version 1.5.3 and onward.
