### ISSUE TITLE
Enhancement - Animation while switching from hours to minutes

### ISSUE THREAD

**Issue by Chris2011** [owsolutions/amazing-time-picker#93]
I set the flag changeToMinutes="true" and it works perfect, but I think it could be more smoothly, because it jumps hard after I've chosen an hour. Please have a look at the android time picker when you set a clock for yourself. There you can see, how smooth it switches to the minutes.

Cheers

Chris

**Comment by torabian** [comment]
Thank you for your suggestion Chris;

@yousefsami has a work around this. Now if the animation is available in default, and you can make remove animation if you provide:

```

```

**Comment by Chris2011** [comment]
Great, thx :)
